/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Knedlex.Roblox.Users.ApiV1.Client.OpenAPIDateConverter;

namespace Knedlex.Roblox.Users.ApiV1.Model
{
    /// <summary>
    /// RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse
    /// </summary>
    [DataContract(Name = "Roblox.Web.WebAPI.Models.ApiPageResponse[Roblox.Users.Api.UserSearchResponse]")]
    public partial class RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse" /> class.
        /// </summary>
        /// <param name="previousPageCursor">previousPageCursor.</param>
        /// <param name="nextPageCursor">nextPageCursor.</param>
        /// <param name="data">data.</param>
        public RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse(string previousPageCursor = default(string), string nextPageCursor = default(string), List<RobloxUsersApiUserSearchResponse> data = default(List<RobloxUsersApiUserSearchResponse>))
        {
            this.PreviousPageCursor = previousPageCursor;
            this.NextPageCursor = nextPageCursor;
            this.Data = data;
        }

        /// <summary>
        /// Gets or Sets PreviousPageCursor
        /// </summary>
        [DataMember(Name = "previousPageCursor", EmitDefaultValue = false)]
        public string PreviousPageCursor { get; set; }

        /// <summary>
        /// Gets or Sets NextPageCursor
        /// </summary>
        [DataMember(Name = "nextPageCursor", EmitDefaultValue = false)]
        public string NextPageCursor { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public List<RobloxUsersApiUserSearchResponse> Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse {\n");
            sb.Append("  PreviousPageCursor: ").Append(PreviousPageCursor).Append("\n");
            sb.Append("  NextPageCursor: ").Append(NextPageCursor).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
