/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Knedlex.Roblox.Users.ApiV1.Client;
using Knedlex.Roblox.Users.ApiV1.Model;

namespace Knedlex.Roblox.Users.ApiV1.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserSearchApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Searches for users by keyword.
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Users.ApiV1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyword">The search keyword.</param>
        /// <param name="sessionId"> (optional)</param>
        /// <param name="limit">The number of results per request. (optional, default to 10)</param>
        /// <param name="cursor">The paging cursor for the previous or next page. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse</returns>
        RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse V1UsersSearchGet(string keyword, string sessionId = default(string), int? limit = default(int?), string cursor = default(string), int operationIndex = 0);

        /// <summary>
        /// Searches for users by keyword.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knedlex.Roblox.Users.ApiV1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyword">The search keyword.</param>
        /// <param name="sessionId"> (optional)</param>
        /// <param name="limit">The number of results per request. (optional, default to 10)</param>
        /// <param name="cursor">The paging cursor for the previous or next page. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse</returns>
        ApiResponse<RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse> V1UsersSearchGetWithHttpInfo(string keyword, string sessionId = default(string), int? limit = default(int?), string cursor = default(string), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserSearchApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Searches for users by keyword.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knedlex.Roblox.Users.ApiV1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyword">The search keyword.</param>
        /// <param name="sessionId"> (optional)</param>
        /// <param name="limit">The number of results per request. (optional, default to 10)</param>
        /// <param name="cursor">The paging cursor for the previous or next page. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse</returns>
        System.Threading.Tasks.Task<RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse> V1UsersSearchGetAsync(string keyword, string sessionId = default(string), int? limit = default(int?), string cursor = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Searches for users by keyword.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knedlex.Roblox.Users.ApiV1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyword">The search keyword.</param>
        /// <param name="sessionId"> (optional)</param>
        /// <param name="limit">The number of results per request. (optional, default to 10)</param>
        /// <param name="cursor">The paging cursor for the previous or next page. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse>> V1UsersSearchGetWithHttpInfoAsync(string keyword, string sessionId = default(string), int? limit = default(int?), string cursor = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserSearchApi : IUserSearchApiSync, IUserSearchApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UserSearchApi : IUserSearchApi
    {
        private Knedlex.Roblox.Users.ApiV1.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UserSearchApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UserSearchApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserSearchApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UserSearchApi(string basePath)
        {
            this.Configuration = Knedlex.Roblox.Users.ApiV1.Client.Configuration.MergeConfigurations(
                Knedlex.Roblox.Users.ApiV1.Client.GlobalConfiguration.Instance,
                new Knedlex.Roblox.Users.ApiV1.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Knedlex.Roblox.Users.ApiV1.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Knedlex.Roblox.Users.ApiV1.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Knedlex.Roblox.Users.ApiV1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserSearchApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UserSearchApi(Knedlex.Roblox.Users.ApiV1.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Knedlex.Roblox.Users.ApiV1.Client.Configuration.MergeConfigurations(
                Knedlex.Roblox.Users.ApiV1.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Knedlex.Roblox.Users.ApiV1.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Knedlex.Roblox.Users.ApiV1.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Knedlex.Roblox.Users.ApiV1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserSearchApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public UserSearchApi(Knedlex.Roblox.Users.ApiV1.Client.ISynchronousClient client, Knedlex.Roblox.Users.ApiV1.Client.IAsynchronousClient asyncClient, Knedlex.Roblox.Users.ApiV1.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Knedlex.Roblox.Users.ApiV1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Knedlex.Roblox.Users.ApiV1.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Knedlex.Roblox.Users.ApiV1.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Knedlex.Roblox.Users.ApiV1.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Knedlex.Roblox.Users.ApiV1.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Searches for users by keyword. 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Users.ApiV1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyword">The search keyword.</param>
        /// <param name="sessionId"> (optional)</param>
        /// <param name="limit">The number of results per request. (optional, default to 10)</param>
        /// <param name="cursor">The paging cursor for the previous or next page. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse</returns>
        public RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse V1UsersSearchGet(string keyword, string sessionId = default(string), int? limit = default(int?), string cursor = default(string), int operationIndex = 0)
        {
            Knedlex.Roblox.Users.ApiV1.Client.ApiResponse<RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse> localVarResponse = V1UsersSearchGetWithHttpInfo(keyword, sessionId, limit, cursor);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Searches for users by keyword. 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Users.ApiV1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyword">The search keyword.</param>
        /// <param name="sessionId"> (optional)</param>
        /// <param name="limit">The number of results per request. (optional, default to 10)</param>
        /// <param name="cursor">The paging cursor for the previous or next page. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse</returns>
        public Knedlex.Roblox.Users.ApiV1.Client.ApiResponse<RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse> V1UsersSearchGetWithHttpInfo(string keyword, string sessionId = default(string), int? limit = default(int?), string cursor = default(string), int operationIndex = 0)
        {
            // verify the required parameter 'keyword' is set
            if (keyword == null)
            {
                throw new Knedlex.Roblox.Users.ApiV1.Client.ApiException(400, "Missing required parameter 'keyword' when calling UserSearchApi->V1UsersSearchGet");
            }

            Knedlex.Roblox.Users.ApiV1.Client.RequestOptions localVarRequestOptions = new Knedlex.Roblox.Users.ApiV1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "text/json"
            };

            var localVarContentType = Knedlex.Roblox.Users.ApiV1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Knedlex.Roblox.Users.ApiV1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Users.ApiV1.Client.ClientUtils.ParameterToMultiMap("", "keyword", keyword));
            if (sessionId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Users.ApiV1.Client.ClientUtils.ParameterToMultiMap("", "sessionId", sessionId));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Users.ApiV1.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Users.ApiV1.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            localVarRequestOptions.Operation = "UserSearchApi.V1UsersSearchGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse>("/v1/users/search", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("V1UsersSearchGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Searches for users by keyword. 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Users.ApiV1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyword">The search keyword.</param>
        /// <param name="sessionId"> (optional)</param>
        /// <param name="limit">The number of results per request. (optional, default to 10)</param>
        /// <param name="cursor">The paging cursor for the previous or next page. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse</returns>
        public async System.Threading.Tasks.Task<RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse> V1UsersSearchGetAsync(string keyword, string sessionId = default(string), int? limit = default(int?), string cursor = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Knedlex.Roblox.Users.ApiV1.Client.ApiResponse<RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse> localVarResponse = await V1UsersSearchGetWithHttpInfoAsync(keyword, sessionId, limit, cursor, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Searches for users by keyword. 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Users.ApiV1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyword">The search keyword.</param>
        /// <param name="sessionId"> (optional)</param>
        /// <param name="limit">The number of results per request. (optional, default to 10)</param>
        /// <param name="cursor">The paging cursor for the previous or next page. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse)</returns>
        public async System.Threading.Tasks.Task<Knedlex.Roblox.Users.ApiV1.Client.ApiResponse<RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse>> V1UsersSearchGetWithHttpInfoAsync(string keyword, string sessionId = default(string), int? limit = default(int?), string cursor = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'keyword' is set
            if (keyword == null)
            {
                throw new Knedlex.Roblox.Users.ApiV1.Client.ApiException(400, "Missing required parameter 'keyword' when calling UserSearchApi->V1UsersSearchGet");
            }


            Knedlex.Roblox.Users.ApiV1.Client.RequestOptions localVarRequestOptions = new Knedlex.Roblox.Users.ApiV1.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "text/json"
            };

            var localVarContentType = Knedlex.Roblox.Users.ApiV1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Knedlex.Roblox.Users.ApiV1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Users.ApiV1.Client.ClientUtils.ParameterToMultiMap("", "keyword", keyword));
            if (sessionId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Users.ApiV1.Client.ClientUtils.ParameterToMultiMap("", "sessionId", sessionId));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Users.ApiV1.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Users.ApiV1.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            localVarRequestOptions.Operation = "UserSearchApi.V1UsersSearchGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse>("/v1/users/search", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("V1UsersSearchGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
