/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Knedlex.Roblox.Users.ApiV1.Client;
using Knedlex.Roblox.Users.ApiV1.Api;
// uncomment below to import models
//using Knedlex.Roblox.Users.ApiV1.Model;

namespace Knedlex.Roblox.Users.ApiV1.Test.Api
{
    /// <summary>
    ///  Class for testing AccountInformationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AccountInformationApiTests : IDisposable
    {
        private AccountInformationApi instance;

        public AccountInformationApiTests()
        {
            instance = new AccountInformationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountInformationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AccountInformationApi
            //Assert.IsType<AccountInformationApi>(instance);
        }

        /// <summary>
        /// Test V1BirthdateGet
        /// </summary>
        [Fact]
        public void V1BirthdateGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1BirthdateGet();
            //Assert.IsType<RobloxUsersApiBirthdateResponse>(response);
        }

        /// <summary>
        /// Test V1BirthdatePost
        /// </summary>
        [Fact]
        public void V1BirthdatePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RobloxUsersApiBirthdateRequest request = null;
            //var response = instance.V1BirthdatePost(request);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test V1DescriptionGet
        /// </summary>
        [Fact]
        public void V1DescriptionGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1DescriptionGet();
            //Assert.IsType<RobloxUsersApiDescriptionResponse>(response);
        }

        /// <summary>
        /// Test V1DescriptionPost
        /// </summary>
        [Fact]
        public void V1DescriptionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RobloxUsersApiDescriptionRequest request = null;
            //var response = instance.V1DescriptionPost(request);
            //Assert.IsType<RobloxUsersApiDescriptionResponse>(response);
        }

        /// <summary>
        /// Test V1GenderGet
        /// </summary>
        [Fact]
        public void V1GenderGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1GenderGet();
            //Assert.IsType<RobloxUsersApiGenderResponse>(response);
        }

        /// <summary>
        /// Test V1GenderPost
        /// </summary>
        [Fact]
        public void V1GenderPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RobloxUsersApiGenderRequest request = null;
            //var response = instance.V1GenderPost(request);
            //Assert.IsType<Object>(response);
        }
    }
}
