/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Knedlex.Roblox.Users.ApiV1.Client;
using Knedlex.Roblox.Users.ApiV1.Api;
// uncomment below to import models
//using Knedlex.Roblox.Users.ApiV1.Model;

namespace Knedlex.Roblox.Users.ApiV1.Test.Api
{
    /// <summary>
    ///  Class for testing DisplayNamesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DisplayNamesApiTests : IDisposable
    {
        private DisplayNamesApi instance;

        public DisplayNamesApiTests()
        {
            instance = new DisplayNamesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DisplayNamesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DisplayNamesApi
            //Assert.IsType<DisplayNamesApi>(instance);
        }

        /// <summary>
        /// Test V1DisplayNamesValidateGet
        /// </summary>
        [Fact]
        public void V1DisplayNamesValidateGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string displayName = null;
            //DateTime birthdate = null;
            //var response = instance.V1DisplayNamesValidateGet(displayName, birthdate);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test V1UsersUserIdDisplayNamesPatch
        /// </summary>
        [Fact]
        public void V1UsersUserIdDisplayNamesPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long userId = null;
            //RobloxUsersApiSetDisplayNameRequest request = null;
            //var response = instance.V1UsersUserIdDisplayNamesPatch(userId, request);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test V1UsersUserIdDisplayNamesValidateGet
        /// </summary>
        [Fact]
        public void V1UsersUserIdDisplayNamesValidateGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long userId = null;
            //string displayName = null;
            //var response = instance.V1UsersUserIdDisplayNamesValidateGet(userId, displayName);
            //Assert.IsType<Object>(response);
        }
    }
}
