/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Knedlex.Roblox.Users.ApiV1.Client;
using Knedlex.Roblox.Users.ApiV1.Api;
// uncomment below to import models
//using Knedlex.Roblox.Users.ApiV1.Model;

namespace Knedlex.Roblox.Users.ApiV1.Test.Api
{
    /// <summary>
    ///  Class for testing UsersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UsersApiTests : IDisposable
    {
        private UsersApi instance;

        public UsersApiTests()
        {
            instance = new UsersApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UsersApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' UsersApi
            //Assert.IsType<UsersApi>(instance);
        }

        /// <summary>
        /// Test V1UsernamesUsersPost
        /// </summary>
        [Fact]
        public void V1UsernamesUsersPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RobloxUsersApiMultiGetByUsernameRequest request = null;
            //var response = instance.V1UsernamesUsersPost(request);
            //Assert.IsType<RobloxWebWebAPIModelsApiArrayResponseRobloxUsersApiMultiGetUserByNameResponse>(response);
        }

        /// <summary>
        /// Test V1UsersAuthenticatedAgeBracketGet
        /// </summary>
        [Fact]
        public void V1UsersAuthenticatedAgeBracketGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1UsersAuthenticatedAgeBracketGet();
            //Assert.IsType<RobloxUsersApiUserAgeBracketResponse>(response);
        }

        /// <summary>
        /// Test V1UsersAuthenticatedCountryCodeGet
        /// </summary>
        [Fact]
        public void V1UsersAuthenticatedCountryCodeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1UsersAuthenticatedCountryCodeGet();
            //Assert.IsType<RobloxUsersApiUserCountryCodeResponse>(response);
        }

        /// <summary>
        /// Test V1UsersAuthenticatedGet
        /// </summary>
        [Fact]
        public void V1UsersAuthenticatedGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1UsersAuthenticatedGet();
            //Assert.IsType<RobloxUsersApiAuthenticatedUserResponse>(response);
        }

        /// <summary>
        /// Test V1UsersAuthenticatedRolesGet
        /// </summary>
        [Fact]
        public void V1UsersAuthenticatedRolesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1UsersAuthenticatedRolesGet();
            //Assert.IsType<RobloxUsersApiUserRolesResponse>(response);
        }

        /// <summary>
        /// Test V1UsersPost
        /// </summary>
        [Fact]
        public void V1UsersPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RobloxUsersApiMultiGetByUserIdRequest request = null;
            //var response = instance.V1UsersPost(request);
            //Assert.IsType<RobloxWebWebAPIModelsApiArrayResponseRobloxUsersApiVerifiedBadgeUserResponse>(response);
        }

        /// <summary>
        /// Test V1UsersUserIdGet
        /// </summary>
        [Fact]
        public void V1UsersUserIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long userId = null;
            //var response = instance.V1UsersUserIdGet(userId);
            //Assert.IsType<RobloxUsersApiGetUserResponse>(response);
        }
    }
}
