/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Knedlex.Roblox.Users.ApiV1.Client;
using Knedlex.Roblox.Users.ApiV1.Api;
// uncomment below to import models
//using Knedlex.Roblox.Users.ApiV1.Model;

namespace Knedlex.Roblox.Users.ApiV1.Test.Api
{
    /// <summary>
    ///  Class for testing UserSearchApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UserSearchApiTests : IDisposable
    {
        private UserSearchApi instance;

        public UserSearchApiTests()
        {
            instance = new UserSearchApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserSearchApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' UserSearchApi
            //Assert.IsType<UserSearchApi>(instance);
        }

        /// <summary>
        /// Test V1UsersSearchGet
        /// </summary>
        [Fact]
        public void V1UsersSearchGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string keyword = null;
            //string sessionId = null;
            //int? limit = null;
            //string cursor = null;
            //var response = instance.V1UsersSearchGet(keyword, sessionId, limit, cursor);
            //Assert.IsType<RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse>(response);
        }
    }
}
