/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Users.ApiV1.Model;
using Knedlex.Roblox.Users.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Users.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxUsersApiSetDisplayNameRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxUsersApiSetDisplayNameRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxUsersApiSetDisplayNameRequest
        //private RobloxUsersApiSetDisplayNameRequest instance;

        public RobloxUsersApiSetDisplayNameRequestTests()
        {
            // TODO uncomment below to create an instance of RobloxUsersApiSetDisplayNameRequest
            //instance = new RobloxUsersApiSetDisplayNameRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxUsersApiSetDisplayNameRequest
        /// </summary>
        [Fact]
        public void RobloxUsersApiSetDisplayNameRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxUsersApiSetDisplayNameRequest
            //Assert.IsType<RobloxUsersApiSetDisplayNameRequest>(instance);
        }

        /// <summary>
        /// Test the property 'NewDisplayName'
        /// </summary>
        [Fact]
        public void NewDisplayNameTest()
        {
            // TODO unit test for the property 'NewDisplayName'
        }
    }
}
