/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Users.ApiV1.Model;
using Knedlex.Roblox.Users.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Users.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse
        //private RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse instance;

        public RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponseTests()
        {
            // TODO uncomment below to create an instance of RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse
            //instance = new RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse
        /// </summary>
        [Fact]
        public void RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse
            //Assert.IsType<RobloxWebWebAPIModelsApiPageResponseRobloxUsersApiUserSearchResponse>(instance);
        }

        /// <summary>
        /// Test the property 'PreviousPageCursor'
        /// </summary>
        [Fact]
        public void PreviousPageCursorTest()
        {
            // TODO unit test for the property 'PreviousPageCursor'
        }

        /// <summary>
        /// Test the property 'NextPageCursor'
        /// </summary>
        [Fact]
        public void NextPageCursorTest()
        {
            // TODO unit test for the property 'NextPageCursor'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
