/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Users.ApiV1.Model;
using Knedlex.Roblox.Users.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Users.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxUsersApiUserAgeBracketResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxUsersApiUserAgeBracketResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxUsersApiUserAgeBracketResponse
        //private RobloxUsersApiUserAgeBracketResponse instance;

        public RobloxUsersApiUserAgeBracketResponseTests()
        {
            // TODO uncomment below to create an instance of RobloxUsersApiUserAgeBracketResponse
            //instance = new RobloxUsersApiUserAgeBracketResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxUsersApiUserAgeBracketResponse
        /// </summary>
        [Fact]
        public void RobloxUsersApiUserAgeBracketResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxUsersApiUserAgeBracketResponse
            //Assert.IsType<RobloxUsersApiUserAgeBracketResponse>(instance);
        }

        /// <summary>
        /// Test the property 'AgeBracket'
        /// </summary>
        [Fact]
        public void AgeBracketTest()
        {
            // TODO unit test for the property 'AgeBracket'
        }
    }
}
