/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Users.ApiV1.Model;
using Knedlex.Roblox.Users.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Users.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxUsersApiGenderRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxUsersApiGenderRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxUsersApiGenderRequest
        //private RobloxUsersApiGenderRequest instance;

        public RobloxUsersApiGenderRequestTests()
        {
            // TODO uncomment below to create an instance of RobloxUsersApiGenderRequest
            //instance = new RobloxUsersApiGenderRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxUsersApiGenderRequest
        /// </summary>
        [Fact]
        public void RobloxUsersApiGenderRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxUsersApiGenderRequest
            //Assert.IsType<RobloxUsersApiGenderRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
    }
}
