/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Users.ApiV1.Model;
using Knedlex.Roblox.Users.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Users.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxWebWebAPIModelsApiArrayResponseRobloxUsersApiMultiGetUserByNameResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxWebWebAPIModelsApiArrayResponseRobloxUsersApiMultiGetUserByNameResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxWebWebAPIModelsApiArrayResponseRobloxUsersApiMultiGetUserByNameResponse
        //private RobloxWebWebAPIModelsApiArrayResponseRobloxUsersApiMultiGetUserByNameResponse instance;

        public RobloxWebWebAPIModelsApiArrayResponseRobloxUsersApiMultiGetUserByNameResponseTests()
        {
            // TODO uncomment below to create an instance of RobloxWebWebAPIModelsApiArrayResponseRobloxUsersApiMultiGetUserByNameResponse
            //instance = new RobloxWebWebAPIModelsApiArrayResponseRobloxUsersApiMultiGetUserByNameResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxWebWebAPIModelsApiArrayResponseRobloxUsersApiMultiGetUserByNameResponse
        /// </summary>
        [Fact]
        public void RobloxWebWebAPIModelsApiArrayResponseRobloxUsersApiMultiGetUserByNameResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxWebWebAPIModelsApiArrayResponseRobloxUsersApiMultiGetUserByNameResponse
            //Assert.IsType<RobloxWebWebAPIModelsApiArrayResponseRobloxUsersApiMultiGetUserByNameResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
