/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Users.ApiV1.Model;
using Knedlex.Roblox.Users.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Users.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxUsersApiAuthenticatedUserResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxUsersApiAuthenticatedUserResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxUsersApiAuthenticatedUserResponse
        //private RobloxUsersApiAuthenticatedUserResponse instance;

        public RobloxUsersApiAuthenticatedUserResponseTests()
        {
            // TODO uncomment below to create an instance of RobloxUsersApiAuthenticatedUserResponse
            //instance = new RobloxUsersApiAuthenticatedUserResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxUsersApiAuthenticatedUserResponse
        /// </summary>
        [Fact]
        public void RobloxUsersApiAuthenticatedUserResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxUsersApiAuthenticatedUserResponse
            //Assert.IsType<RobloxUsersApiAuthenticatedUserResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
    }
}
