/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Users.ApiV1.Model;
using Knedlex.Roblox.Users.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Users.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxUsersApiBirthdateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxUsersApiBirthdateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxUsersApiBirthdateRequest
        //private RobloxUsersApiBirthdateRequest instance;

        public RobloxUsersApiBirthdateRequestTests()
        {
            // TODO uncomment below to create an instance of RobloxUsersApiBirthdateRequest
            //instance = new RobloxUsersApiBirthdateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxUsersApiBirthdateRequest
        /// </summary>
        [Fact]
        public void RobloxUsersApiBirthdateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxUsersApiBirthdateRequest
            //Assert.IsType<RobloxUsersApiBirthdateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'BirthMonth'
        /// </summary>
        [Fact]
        public void BirthMonthTest()
        {
            // TODO unit test for the property 'BirthMonth'
        }

        /// <summary>
        /// Test the property 'BirthDay'
        /// </summary>
        [Fact]
        public void BirthDayTest()
        {
            // TODO unit test for the property 'BirthDay'
        }

        /// <summary>
        /// Test the property 'BirthYear'
        /// </summary>
        [Fact]
        public void BirthYearTest()
        {
            // TODO unit test for the property 'BirthYear'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
    }
}
