/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Users.ApiV1.Model;
using Knedlex.Roblox.Users.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Users.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxUsersApiUserCountryCodeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxUsersApiUserCountryCodeResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxUsersApiUserCountryCodeResponse
        //private RobloxUsersApiUserCountryCodeResponse instance;

        public RobloxUsersApiUserCountryCodeResponseTests()
        {
            // TODO uncomment below to create an instance of RobloxUsersApiUserCountryCodeResponse
            //instance = new RobloxUsersApiUserCountryCodeResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxUsersApiUserCountryCodeResponse
        /// </summary>
        [Fact]
        public void RobloxUsersApiUserCountryCodeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxUsersApiUserCountryCodeResponse
            //Assert.IsType<RobloxUsersApiUserCountryCodeResponse>(instance);
        }

        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Fact]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
    }
}
