/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Users.ApiV1.Model;
using Knedlex.Roblox.Users.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Users.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxUsersApiMultiGetByUsernameRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxUsersApiMultiGetByUsernameRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxUsersApiMultiGetByUsernameRequest
        //private RobloxUsersApiMultiGetByUsernameRequest instance;

        public RobloxUsersApiMultiGetByUsernameRequestTests()
        {
            // TODO uncomment below to create an instance of RobloxUsersApiMultiGetByUsernameRequest
            //instance = new RobloxUsersApiMultiGetByUsernameRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxUsersApiMultiGetByUsernameRequest
        /// </summary>
        [Fact]
        public void RobloxUsersApiMultiGetByUsernameRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxUsersApiMultiGetByUsernameRequest
            //Assert.IsType<RobloxUsersApiMultiGetByUsernameRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Usernames'
        /// </summary>
        [Fact]
        public void UsernamesTest()
        {
            // TODO unit test for the property 'Usernames'
        }

        /// <summary>
        /// Test the property 'ExcludeBannedUsers'
        /// </summary>
        [Fact]
        public void ExcludeBannedUsersTest()
        {
            // TODO unit test for the property 'ExcludeBannedUsers'
        }
    }
}
