/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Users.ApiV1.Model;
using Knedlex.Roblox.Users.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Users.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxUsersApiGetUserResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxUsersApiGetUserResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxUsersApiGetUserResponse
        //private RobloxUsersApiGetUserResponse instance;

        public RobloxUsersApiGetUserResponseTests()
        {
            // TODO uncomment below to create an instance of RobloxUsersApiGetUserResponse
            //instance = new RobloxUsersApiGetUserResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxUsersApiGetUserResponse
        /// </summary>
        [Fact]
        public void RobloxUsersApiGetUserResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxUsersApiGetUserResponse
            //Assert.IsType<RobloxUsersApiGetUserResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'IsBanned'
        /// </summary>
        [Fact]
        public void IsBannedTest()
        {
            // TODO unit test for the property 'IsBanned'
        }

        /// <summary>
        /// Test the property 'ExternalAppDisplayName'
        /// </summary>
        [Fact]
        public void ExternalAppDisplayNameTest()
        {
            // TODO unit test for the property 'ExternalAppDisplayName'
        }

        /// <summary>
        /// Test the property 'HasVerifiedBadge'
        /// </summary>
        [Fact]
        public void HasVerifiedBadgeTest()
        {
            // TODO unit test for the property 'HasVerifiedBadge'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
    }
}
