/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Users.ApiV1.Model;
using Knedlex.Roblox.Users.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Users.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxUsersApiGenderResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxUsersApiGenderResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxUsersApiGenderResponse
        //private RobloxUsersApiGenderResponse instance;

        public RobloxUsersApiGenderResponseTests()
        {
            // TODO uncomment below to create an instance of RobloxUsersApiGenderResponse
            //instance = new RobloxUsersApiGenderResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxUsersApiGenderResponse
        /// </summary>
        [Fact]
        public void RobloxUsersApiGenderResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxUsersApiGenderResponse
            //Assert.IsType<RobloxUsersApiGenderResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
    }
}
