/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Users.ApiV1.Model;
using Knedlex.Roblox.Users.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Users.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxUsersApiDescriptionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxUsersApiDescriptionResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxUsersApiDescriptionResponse
        //private RobloxUsersApiDescriptionResponse instance;

        public RobloxUsersApiDescriptionResponseTests()
        {
            // TODO uncomment below to create an instance of RobloxUsersApiDescriptionResponse
            //instance = new RobloxUsersApiDescriptionResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxUsersApiDescriptionResponse
        /// </summary>
        [Fact]
        public void RobloxUsersApiDescriptionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxUsersApiDescriptionResponse
            //Assert.IsType<RobloxUsersApiDescriptionResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
