/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Users.ApiV1.Model;
using Knedlex.Roblox.Users.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Users.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxUsersApiMultiGetByUserIdRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxUsersApiMultiGetByUserIdRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxUsersApiMultiGetByUserIdRequest
        //private RobloxUsersApiMultiGetByUserIdRequest instance;

        public RobloxUsersApiMultiGetByUserIdRequestTests()
        {
            // TODO uncomment below to create an instance of RobloxUsersApiMultiGetByUserIdRequest
            //instance = new RobloxUsersApiMultiGetByUserIdRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxUsersApiMultiGetByUserIdRequest
        /// </summary>
        [Fact]
        public void RobloxUsersApiMultiGetByUserIdRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxUsersApiMultiGetByUserIdRequest
            //Assert.IsType<RobloxUsersApiMultiGetByUserIdRequest>(instance);
        }

        /// <summary>
        /// Test the property 'UserIds'
        /// </summary>
        [Fact]
        public void UserIdsTest()
        {
            // TODO unit test for the property 'UserIds'
        }

        /// <summary>
        /// Test the property 'ExcludeBannedUsers'
        /// </summary>
        [Fact]
        public void ExcludeBannedUsersTest()
        {
            // TODO unit test for the property 'ExcludeBannedUsers'
        }
    }
}
