/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Users.ApiV1.Model;
using Knedlex.Roblox.Users.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Users.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64
        //private RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64 instance;

        public RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64Tests()
        {
            // TODO uncomment below to create an instance of RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64
            //instance = new RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64
        /// </summary>
        [Fact]
        public void RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64InstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64
            //Assert.IsType<RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'SortOrder'
        /// </summary>
        [Fact]
        public void SortOrderTest()
        {
            // TODO unit test for the property 'SortOrder'
        }

        /// <summary>
        /// Test the property 'PagingDirection'
        /// </summary>
        [Fact]
        public void PagingDirectionTest()
        {
            // TODO unit test for the property 'PagingDirection'
        }

        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Fact]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }

        /// <summary>
        /// Test the property 'Discriminator'
        /// </summary>
        [Fact]
        public void DiscriminatorTest()
        {
            // TODO unit test for the property 'Discriminator'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
    }
}
