/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Users.ApiV1.Model;
using Knedlex.Roblox.Users.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Users.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxUsersApiUserRolesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxUsersApiUserRolesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxUsersApiUserRolesResponse
        //private RobloxUsersApiUserRolesResponse instance;

        public RobloxUsersApiUserRolesResponseTests()
        {
            // TODO uncomment below to create an instance of RobloxUsersApiUserRolesResponse
            //instance = new RobloxUsersApiUserRolesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxUsersApiUserRolesResponse
        /// </summary>
        [Fact]
        public void RobloxUsersApiUserRolesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxUsersApiUserRolesResponse
            //Assert.IsType<RobloxUsersApiUserRolesResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }
    }
}
