/*
 * Users Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Users.ApiV1.Model;
using Knedlex.Roblox.Users.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Users.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxPagingStartIndexCursor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxPagingStartIndexCursorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxPagingStartIndexCursor
        //private RobloxPagingStartIndexCursor instance;

        public RobloxPagingStartIndexCursorTests()
        {
            // TODO uncomment below to create an instance of RobloxPagingStartIndexCursor
            //instance = new RobloxPagingStartIndexCursor();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxPagingStartIndexCursor
        /// </summary>
        [Fact]
        public void RobloxPagingStartIndexCursorInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxPagingStartIndexCursor
            //Assert.IsType<RobloxPagingStartIndexCursor>(instance);
        }

        /// <summary>
        /// Test the property 'StartIndex'
        /// </summary>
        [Fact]
        public void StartIndexTest()
        {
            // TODO unit test for the property 'StartIndex'
        }

        /// <summary>
        /// Test the property 'Discriminator'
        /// </summary>
        [Fact]
        public void DiscriminatorTest()
        {
            // TODO unit test for the property 'Discriminator'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
    }
}
